/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dormitory_management_system;

import java.awt.Color;
import java.awt.HeadlessException;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.showMessageDialog;
import javax.swing.JTextField;

/**
 *
 * @author James Patrick
 */
public class Registration_Window extends javax.swing.JFrame {

    /**
     * Creates new form Registration_Window
     */
    public Registration_Window() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        FirstName_Register = new javax.swing.JTextField();
        LastName_Register = new javax.swing.JTextField();
        EmailAddress_Register = new javax.swing.JTextField();
        MobileNumber_Register = new javax.swing.JTextField();
        Birthday_Register = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        Username_Register = new javax.swing.JTextField();
        Sign_Button = new javax.swing.JButton();
        Password_Register = new javax.swing.JPasswordField();
        ConfirmPassword_Register = new javax.swing.JPasswordField();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(562, 222));
        setResizable(false);

        FirstName_Register.setForeground(new java.awt.Color(153, 153, 153));
        FirstName_Register.setText("First Name");
        FirstName_Register.setToolTipText("");
        FirstName_Register.setCaretColor(new java.awt.Color(153, 153, 153));
        FirstName_Register.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                FirstName_RegisterFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                FirstName_RegisterFocusLost(evt);
            }
        });
        FirstName_Register.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FirstName_RegisterMouseClicked(evt);
            }
        });
        FirstName_Register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FirstName_RegisterActionPerformed(evt);
            }
        });

        LastName_Register.setForeground(new java.awt.Color(153, 153, 153));
        LastName_Register.setText("Last Name");
        LastName_Register.setToolTipText("");
        LastName_Register.setCaretColor(new java.awt.Color(153, 153, 153));
        LastName_Register.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                LastName_RegisterFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                LastName_RegisterFocusLost(evt);
            }
        });
        LastName_Register.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LastName_RegisterMouseClicked(evt);
            }
        });
        LastName_Register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LastName_RegisterActionPerformed(evt);
            }
        });

        EmailAddress_Register.setForeground(new java.awt.Color(153, 153, 153));
        EmailAddress_Register.setText("Email Address");
        EmailAddress_Register.setToolTipText("");
        EmailAddress_Register.setCaretColor(new java.awt.Color(153, 153, 153));
        EmailAddress_Register.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                EmailAddress_RegisterFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                EmailAddress_RegisterFocusLost(evt);
            }
        });
        EmailAddress_Register.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EmailAddress_RegisterMouseClicked(evt);
            }
        });
        EmailAddress_Register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailAddress_RegisterActionPerformed(evt);
            }
        });

        MobileNumber_Register.setForeground(new java.awt.Color(153, 153, 153));
        MobileNumber_Register.setText("Mobile Number");
        MobileNumber_Register.setToolTipText("");
        MobileNumber_Register.setCaretColor(new java.awt.Color(153, 153, 153));
        MobileNumber_Register.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                MobileNumber_RegisterFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                MobileNumber_RegisterFocusLost(evt);
            }
        });
        MobileNumber_Register.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MobileNumber_RegisterMouseClicked(evt);
            }
        });
        MobileNumber_Register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MobileNumber_RegisterActionPerformed(evt);
            }
        });

        Birthday_Register.setDateFormatString("yyyy-MM-dd");

        jLabel1.setText("Birthday");

        Username_Register.setForeground(new java.awt.Color(153, 153, 153));
        Username_Register.setText("Enter your Username");
        Username_Register.setToolTipText("");
        Username_Register.setCaretColor(new java.awt.Color(153, 153, 153));
        Username_Register.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Username_RegisterFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                Username_RegisterFocusLost(evt);
            }
        });
        Username_Register.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Username_RegisterMouseClicked(evt);
            }
        });
        Username_Register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Username_RegisterActionPerformed(evt);
            }
        });

        Sign_Button.setText("Sign in");
        Sign_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sign_ButtonActionPerformed(evt);
            }
        });

        Password_Register.setForeground(new java.awt.Color(153, 153, 153));
        Password_Register.setText("Password");
        Password_Register.setEchoChar('\u0000');
        Password_Register.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Password_RegisterFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                Password_RegisterFocusLost(evt);
            }
        });

        ConfirmPassword_Register.setForeground(new java.awt.Color(153, 153, 153));
        ConfirmPassword_Register.setText("Confirm Password");
        ConfirmPassword_Register.setEchoChar('\u0000');
        ConfirmPassword_Register.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ConfirmPassword_RegisterFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                ConfirmPassword_RegisterFocusLost(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(Birthday_Register, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addComponent(Sign_Button))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(EmailAddress_Register, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(FirstName_Register, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(LastName_Register, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(MobileNumber_Register)
                            .addComponent(Username_Register)
                            .addComponent(Password_Register)
                            .addComponent(ConfirmPassword_Register, javax.swing.GroupLayout.Alignment.LEADING))))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FirstName_Register, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LastName_Register, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(EmailAddress_Register, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(MobileNumber_Register, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Birthday_Register, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addComponent(Username_Register, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Password_Register, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(ConfirmPassword_Register, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Sign_Button)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FirstName_RegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FirstName_RegisterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FirstName_RegisterActionPerformed

    private void FirstName_RegisterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FirstName_RegisterMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_FirstName_RegisterMouseClicked

    private void FirstName_RegisterFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_FirstName_RegisterFocusGained
        try{
            if(FirstName_Register.getText().equals("First Name")){
                FirstName_Register.setText("");
                FirstName_Register.setForeground(new Color(0,0,0));
            }
        }catch(Exception e){
            System.out.println("Error: " + e.getMessage());
        }
    }//GEN-LAST:event_FirstName_RegisterFocusGained

    private void FirstName_RegisterFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_FirstName_RegisterFocusLost
        try{
            if(FirstName_Register.getText().equals("")){
                FirstName_Register.setText("First Name");
                FirstName_Register.setForeground(new Color(153,153,153));
            }
        }catch(Exception e){
            System.out.println("Error: " + e.getMessage());
        }
    }//GEN-LAST:event_FirstName_RegisterFocusLost

    private void LastName_RegisterFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_LastName_RegisterFocusGained
        try{
            if(LastName_Register.getText().equals("Last Name")){
                LastName_Register.setText("");
                LastName_Register.setForeground(new Color(0,0,0));
            }
        }catch(Exception e){
            System.out.println("Error: " + e.getMessage());
        }
    }//GEN-LAST:event_LastName_RegisterFocusGained

    private void LastName_RegisterFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_LastName_RegisterFocusLost
        try{
            if(LastName_Register.getText().equals("")){
                LastName_Register.setText("Last Name");
                LastName_Register.setForeground(new Color(153,153,153));
            }
        }catch(Exception e){
            System.out.println("Error: " + e.getMessage());
        }
    }//GEN-LAST:event_LastName_RegisterFocusLost

    private void LastName_RegisterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LastName_RegisterMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_LastName_RegisterMouseClicked

    private void LastName_RegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LastName_RegisterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LastName_RegisterActionPerformed

    private void EmailAddress_RegisterFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_EmailAddress_RegisterFocusGained
        try{
            if(EmailAddress_Register.getText().equals("Email Address")){
                EmailAddress_Register.setText("");
                EmailAddress_Register.setForeground(new Color(0,0,0));
            }
        }catch(Exception e){
            System.out.println("Error: " + e.getMessage());
        }
    }//GEN-LAST:event_EmailAddress_RegisterFocusGained

    private void EmailAddress_RegisterFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_EmailAddress_RegisterFocusLost
        try{
            if(EmailAddress_Register.getText().equals("")){
                EmailAddress_Register.setText("Email Address");
                EmailAddress_Register.setForeground(new Color(153,153,153));
            }
        }catch(Exception e){
            System.out.println("Error: " + e.getMessage());
        }
    }//GEN-LAST:event_EmailAddress_RegisterFocusLost

    private void EmailAddress_RegisterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EmailAddress_RegisterMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailAddress_RegisterMouseClicked

    private void EmailAddress_RegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailAddress_RegisterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailAddress_RegisterActionPerformed

    private void MobileNumber_RegisterFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_MobileNumber_RegisterFocusGained
        try{
            if(MobileNumber_Register.getText().equals("Mobile Number")){
                MobileNumber_Register.setText("");
                MobileNumber_Register.setForeground(new Color(0,0,0));
            }
        }catch(Exception e){
            System.out.println("Error: " + e.getMessage());
        }
    }//GEN-LAST:event_MobileNumber_RegisterFocusGained

    private void MobileNumber_RegisterFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_MobileNumber_RegisterFocusLost
        try{
            if(MobileNumber_Register.getText().equals("")){
                MobileNumber_Register.setText("Mobile Number");
                MobileNumber_Register.setForeground(new Color(153,153,153));
            }
        }catch(Exception e){
            System.out.println("Error: " + e.getMessage());
        }
    }//GEN-LAST:event_MobileNumber_RegisterFocusLost

    private void MobileNumber_RegisterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MobileNumber_RegisterMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_MobileNumber_RegisterMouseClicked

    private void MobileNumber_RegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MobileNumber_RegisterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MobileNumber_RegisterActionPerformed

    private void Username_RegisterFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Username_RegisterFocusGained
        try{
            if(Username_Register.getText().equals("Enter your Username")){
                Username_Register.setText("");
                Username_Register.setForeground(new Color(0,0,0));
            }
        }catch(Exception e){
            System.out.println("Error: " + e.getMessage());
        }
    }//GEN-LAST:event_Username_RegisterFocusGained

    private void Username_RegisterFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Username_RegisterFocusLost
        try{
            if(Username_Register.getText().equals("")){
                Username_Register.setText("Enter your Username");
                Username_Register.setForeground(new Color(153,153,153));
            }
        }catch(Exception e){
            System.out.println("Error: " + e.getMessage());
        }
    }//GEN-LAST:event_Username_RegisterFocusLost

    private void Username_RegisterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Username_RegisterMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Username_RegisterMouseClicked

    private void Username_RegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Username_RegisterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Username_RegisterActionPerformed

    private void Sign_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sign_ButtonActionPerformed
        //Registration Input
        String FirstName, LastName, EmailAddress, MobileNumber, Birthday, Username, Password, ConfirmPass, query1,query2,Status;
        String SelectDate = ((JTextField)Birthday_Register.getDateEditor().getUiComponent()).getText();
        try{
            Statement s = Database_Login.mycon().createStatement();
            if("".equals(FirstName_Register.getText()) || "First Name".equals(FirstName_Register.getText())){
                JOptionPane.showMessageDialog(new JFrame(),"First name is required", "Error", JOptionPane.ERROR_MESSAGE);
            }else if("".equals(LastName_Register.getText()) || "Last Name".equals(LastName_Register.getText())){
                JOptionPane.showMessageDialog(new JFrame(),"Last name is required", "Error", JOptionPane.ERROR_MESSAGE);
            }else if("".equals(EmailAddress_Register.getText()) || "Email Address".equals(EmailAddress_Register.getText())){
                JOptionPane.showMessageDialog(new JFrame(),"Email Address is required", "Error", JOptionPane.ERROR_MESSAGE);
            }else if("".equals(MobileNumber_Register.getText()) || "Mobile Number".equals(MobileNumber_Register.getText())){
                JOptionPane.showMessageDialog(new JFrame(),"Mobile Number is required", "Error", JOptionPane.ERROR_MESSAGE);
            }else if("".equals(SelectDate)){
                JOptionPane.showMessageDialog(new JFrame(),"Your Birthday is required", "Error", JOptionPane.ERROR_MESSAGE);
            }else if("".equals(Username_Register.getText()) || "Enter your Username".equals(Username_Register.getText())){
                JOptionPane.showMessageDialog(new JFrame(),"Username is required", "Error", JOptionPane.ERROR_MESSAGE);
            }else if("".equals(Password_Register.getText()) || "Password".equals(Password_Register.getText())){
                JOptionPane.showMessageDialog(new JFrame(),"Password is required", "Error", JOptionPane.ERROR_MESSAGE);
            }else if("".equals(ConfirmPassword_Register.getText()) || "Confirm Password".equals(ConfirmPassword_Register.getText())){
                JOptionPane.showMessageDialog(new JFrame(),"Pls re-enter your Password", "Error", JOptionPane.ERROR_MESSAGE);
            }else if(!ConfirmPassword_Register.getText().equals(Password_Register.getText())){
                JOptionPane.showMessageDialog(new JFrame(),"Password do not match", "Error", JOptionPane.ERROR_MESSAGE);
            }else{
                FirstName    = FirstName_Register.getText();
                LastName     = LastName_Register.getText();
                EmailAddress = EmailAddress_Register.getText();
                MobileNumber = MobileNumber_Register.getText();
                Birthday     = SelectDate;
                Username     = Username_Register.getText();
                Password     = Password_Register.getText();
                ConfirmPass  = ConfirmPassword_Register.getText();
                Status = "Not Verified";
                
                query1 = "INSERT INTO register(First,Last,Email,Mobile,Birth,Username,Password)"
                        + "VALUES('"+FirstName+"','"+LastName+"','"+EmailAddress+"','"+MobileNumber+"','"+Birthday+"','"+Username+"','"+Password+"')";
                
                query2 = "INSERT INTO tenant(First,Last,Email,Mobile,Birth,Username,Password,Status)"
                        + "VALUES('"+FirstName+"','"+LastName+"','"+EmailAddress+"','"+MobileNumber+"','"+Birthday+"','"+Username+"','"+Password+"','"+Status+"')";
                
                
                s.execute(query1);
                s.execute(query2);
                FirstName_Register.setText("");
                LastName_Register.setText("");
                EmailAddress_Register.setText("");
                MobileNumber_Register.setText("");
                Username_Register.setText("");
                Password_Register.setText("");
                ConfirmPassword_Register.setText("");
                showMessageDialog(null,"Your account has been successfully created");
                Login_Window LoginPanel = new Login_Window();
                LoginPanel.setVisible(true);
                LoginPanel.pack();
                LoginPanel.setLocationRelativeTo(null);
                this.dispose();
                }
            
        }catch(HeadlessException e){
            System.out.println("Error: " + e.getMessage());
        } catch (SQLException ex) {
            Logger.getLogger(Registration_Window.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Sign_ButtonActionPerformed

    private void Password_RegisterFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Password_RegisterFocusGained
        try{
            if(Password_Register.getText().equals("Password")){
                Password_Register.setText("");
                Password_Register.setForeground(new Color(0,0,0));
            }
        }catch(Exception e){
            System.out.println("Error: " + e.getMessage());
        }
    }//GEN-LAST:event_Password_RegisterFocusGained

    private void Password_RegisterFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Password_RegisterFocusLost
        try{
            if(Password_Register.getText().equals("")){
                Password_Register.setText("Password");
                Password_Register.setForeground(new Color(153,153,153));
            }
        }catch(Exception e){
            System.out.println("Error: " + e.getMessage());
        }
    }//GEN-LAST:event_Password_RegisterFocusLost

    private void ConfirmPassword_RegisterFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ConfirmPassword_RegisterFocusGained
        try{
            if(ConfirmPassword_Register.getText().equals("Confirm Password")){
                ConfirmPassword_Register.setText("");
                ConfirmPassword_Register.setForeground(new Color(0,0,0));
            }
        }catch(Exception e){
            System.out.println("Error: " + e.getMessage());
        }
    }//GEN-LAST:event_ConfirmPassword_RegisterFocusGained

    private void ConfirmPassword_RegisterFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ConfirmPassword_RegisterFocusLost
        try{
            if(ConfirmPassword_Register.getText().equals("")){
                ConfirmPassword_Register.setText("Confirm Password");
                ConfirmPassword_Register.setForeground(new Color(153,153,153));
            }
        }catch(Exception e){
            System.out.println("Error: " + e.getMessage());
        }
    }//GEN-LAST:event_ConfirmPassword_RegisterFocusLost
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registration_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registration_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registration_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registration_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registration_Window().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser Birthday_Register;
    private javax.swing.JPasswordField ConfirmPassword_Register;
    private javax.swing.JTextField EmailAddress_Register;
    private javax.swing.JTextField FirstName_Register;
    private javax.swing.JTextField LastName_Register;
    private javax.swing.JTextField MobileNumber_Register;
    private javax.swing.JPasswordField Password_Register;
    private javax.swing.JButton Sign_Button;
    private javax.swing.JTextField Username_Register;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
